package io.github.aaroncutress.clipboard

import androidx.compose.runtime.Stable
import androidx.compose.ui.graphics.ImageBitmap
import androidx.compose.ui.text.AnnotatedString
import io.github.aaroncutress.clipboard.html.toHtml
import io.github.aaroncutress.clipboard.internal.ImageCodec

/**
 * Marks the clip builder's receivers, so a `format { }` written in the wrong
 * place fails to compile rather than attaching to the wrong item.
 *
 * Without it, a `text(…)` inside an `item { }` block can resolve against the
 * *outer* [ClipScope] and silently add a second item.
 */
@DslMarker
annotation class ClipDsl

/**
 * Builds the clipboard's contents.
 *
 * ```kotlin
 * clipboard.write {
 *     html("<b>Total:</b> £4.20", plainText = "Total: £4.20")
 *     image(chart)
 * }
 * ```
 *
 * Calls at this level all describe **the same thing** in different forms, which
 * is what a clipboard item is: an application pasting into a plain-text field
 * gets the text, one pasting into a document gets the HTML, one pasting into an
 * image editor gets the PNG, and none of them has to know about the others.
 *
 * For genuinely separate things — three files, four table rows — use [item], and
 * check [ClipboardCapabilities.multipleItems] first, because desktop and the web
 * will keep only the first.
 *
 * @property label A description of the clip, shown to the user by Android's
 *   clipboard UI. Ignored on the three platforms that have nowhere to put it.
 */
@ClipDsl
@Stable
class ClipScope internal constructor() {

    var label: String? = null

    private val items = mutableListOf<ClipItemScope>()
    private val first = ClipItemScope().also { items += it }

    /** Adds plain text. */
    fun text(text: String) = first.text(text)

    /**
     * Adds HTML, and the plain text that goes with it.
     *
     * Both, always — an application pasting into a plain-text field asks for
     * `text/plain` and gets nothing if you only offered HTML. The default
     * strips the tags, which is right often enough to be a default and wrong
     * often enough to be worth overriding.
     */
    fun html(html: String, plainText: String = stripTags(html)) = first.html(html, plainText)

    /** Adds RTF, and the plain text that goes with it. See [html] for why both. */
    fun rtf(rtf: String, plainText: String) = first.rtf(rtf, plainText)

    /**
     * Adds styled text as both HTML and plain text.
     *
     * The HTML is generated by [toHtml], which covers the span types
     * [AnnotatedString] can carry and drops the rest.
     */
    fun annotated(text: AnnotatedString) = first.annotated(text)

    /** Adds an image, encoding it in [format] — [ClipFormat.Png] or [ClipFormat.Jpeg]. */
    fun image(image: ImageBitmap, format: ClipFormat = ClipFormat.Png) = first.image(image, format)

    /** Adds a link, as `text/uri-list` and as plain text. */
    fun uri(uri: String) = first.uri(uri)

    /** Adds raw bytes under [format]. */
    fun bytes(format: ClipFormat, bytes: ByteArray) = first.bytes(format, bytes)

    /**
     * Adds bytes produced on demand.
     *
     * Prefer this for anything expensive. It is also the only shape that works
     * outside a user gesture on the web — Safari accepts a `ClipboardItem` whose
     * values are promises and rejects one built from resolved blobs once the
     * gesture has ended, so a lazy write survives an `await` that an eager one
     * does not.
     */
    fun bytes(format: ClipFormat, load: suspend () -> ByteArray) = first.bytes(format, load)

    /**
     * Adds a file, as an item of its own.
     *
     * Its own item because two files are two things, and an item is one thing in
     * several forms — putting both in one item would mean a clipboard holding a
     * PDF that is also a PNG. Call it twice for two files.
     *
     * See [ClipboardCapabilities.writesFiles]: the web cannot offer a file, only
     * read one.
     */
    fun file(file: ClipFile) {
        item { file(file) }
    }

    /** Adds several files, one item each. Shorthand for [file] in a loop. */
    fun files(files: Iterable<ClipFile>) {
        files.forEach { file(it) }
    }

    /**
     * Adds a further item, separate from the one the calls above build.
     *
     * ```kotlin
     * clipboard.write {
     *     for (row in selection) item { text(row.asTsv()); html(row.asHtml()) }
     * }
     * ```
     *
     * Kept only on Android and iOS — see [ClipboardCapabilities.multipleItems].
     */
    fun item(block: ClipItemScope.() -> Unit) {
        items += ClipItemScope().apply(block)
    }

    internal fun build(): Clip {
        val built = items.map { it.build() }.filter { it.formats.isNotEmpty() }
        require(built.isNotEmpty()) {
            "This clip has no content. `write { }` with an empty body would clear the " +
                "clipboard, which is what `clear()` is for — so it is a mistake rather " +
                "than a shorthand."
        }
        return Clip(label, built)
    }
}

/**
 * Builds one item of a clip: one thing, in one or more representations.
 *
 * Reached through [ClipScope.item]. The single-item case needs none of this —
 * the same functions sit directly on [ClipScope] and apply to its first item.
 */
@ClipDsl
@Stable
class ClipItemScope internal constructor() {

    private val loaders = linkedMapOf<ClipFormat, suspend () -> ByteArray>()

    /** Adds plain text. */
    fun text(text: String) {
        bytes(ClipFormat.PlainText, text.encodeToByteArray())
    }

    /** Adds HTML, and the plain text that goes with it. See [ClipScope.html]. */
    fun html(html: String, plainText: String = stripTags(html)) {
        bytes(ClipFormat.Html, html.encodeToByteArray())
        text(plainText)
    }

    /** Adds RTF, and the plain text that goes with it. */
    fun rtf(rtf: String, plainText: String) {
        bytes(ClipFormat.Rtf, rtf.encodeToByteArray())
        text(plainText)
    }

    /** Adds styled text as both HTML and plain text. */
    fun annotated(text: AnnotatedString) {
        html(text.toHtml(), text.text)
    }

    /**
     * Adds an image, encoded lazily.
     *
     * Lazily because encoding a PNG is the expensive part of copying one, and a
     * caller that offers three formats and whose recipient takes one should pay
     * for one.
     */
    fun image(image: ImageBitmap, format: ClipFormat = ClipFormat.Png) {
        bytes(format) { ImageCodec.encode(image, format) }
    }

    /** Adds a link, as `text/uri-list` and as plain text. */
    fun uri(uri: String) {
        bytes(ClipFormat.UriList, uri.encodeToByteArray())
        text(uri)
    }

    /** Adds raw bytes under [format]. */
    fun bytes(format: ClipFormat, bytes: ByteArray) {
        loaders[format] = { bytes }
    }

    /** Adds bytes produced on demand. See [ClipScope.bytes]. */
    fun bytes(format: ClipFormat, load: suspend () -> ByteArray) {
        loaders[format] = load
    }

    /**
     * Makes this item a file.
     *
     * The item still carries the file's bytes under its own format, so an
     * application that wants the contents rather than the reference — an image
     * editor, a text field — gets them without knowing a file was involved.
     */
    fun file(file: ClipFile) {
        this.file = file
        bytes(file.format) { file.bytes() }
    }

    private var file: ClipFile? = null

    internal fun build(): ClipItem {
        // Copied, so that a scope reused after `build()` cannot mutate a clip
        // that has already been handed to the platform.
        val snapshot = loaders.toMap()
        return ClipItem(snapshot.keys.toSet(), file) { format -> snapshot[format]?.invoke() }
    }
}

/**
 * The plain-text fallback for a fragment of HTML.
 *
 * Not a parser and not trying to be — [io.github.aaroncutress.clipboard.html]
 * has the real one. This drops tags, decodes the five predefined entities plus
 * `&nbsp;`, turns `<br>` and `</p>` into newlines, and collapses the runs of
 * whitespace that leaves behind. It exists so that `html("…")` can offer a
 * `text/plain` representation without the caller having to write one, and the
 * caller can always pass a better one.
 */
internal fun stripTags(html: String): String {
    val text = StringBuilder()
    var inTag = false
    var index = 0
    while (index < html.length) {
        val char = html[index]
        when {
            char == '<' -> {
                // `<br>`, `<br/>`, `</p>`, `</div>`, `<li>` — the tags that are
                // a line break to a reader, whatever they are to a renderer.
                val tag = html.substring(index).takeWhile { it != '>' }.lowercase()
                if (Regex("""^</?(br|p|div|li|tr|h[1-6])\b""").containsMatchIn(tag)) {
                    text.append('\n')
                }
                inTag = true
            }
            char == '>' -> inTag = false
            !inTag -> text.append(char)
        }
        index++
    }
    return text.toString()
        .replace("&nbsp;", " ")
        .replace("&lt;", "<")
        .replace("&gt;", ">")
        .replace("&quot;", "\"")
        .replace("&#39;", "'")
        // Last, so that an escaped `&amp;lt;` does not become a `<`.
        .replace("&amp;", "&")
        .replace(Regex("""[ \t]+"""), " ")
        .replace(Regex("""\n{3,}"""), "\n\n")
        .trim()
}
